### limits-service
GET {{host}}/limits-service/dev

### currency-exchange-service
GET {{host}}/currency-exchange-service/dev

### currency-conversion-service
GET {{host}}/currency-conversion-service/dev